HAI
	WAZZUP
		I HAS A num1
		I HAS A num2
	BUHBYE
	
	VISIBLE "Gimmeh a number: "
	GIMMEH num1

	num2 R 0

	IM IN YR asc UPPIN YR num2 WILE BOTH SAEM num2 AN SMALLR OF num2 AN num1
		VISIBLE num2
	IM OUTTA YR asc

	VISIBLE "***"

	IM IN YR desc NERFIN YR num2 TIL BOTH SAEM num2 AN 0
		VISIBLE num2
	IM OUTTA YR desc


KTHXBYE